branches2 = [
    {
       "id":1,
		"name": "قلنسوة",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":true,
             "video":{
                "name":"قالوا عن مدارس العلوم الشرعية - المهندس فادي عراقي - الطيرة",
                "link":"https://www.youtube.com/watch?v=c2osyZoAhao&list=PLGbHsjcWVUt-gemaZulpjF9oJ6MW3J2vo&index=2&ab_channel=%D9%85%D8%AF%D8%A7%D8%B1%D8%B3%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9"
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"كاملة بدير - كفر قاسم",
                "link":"",
                "details":"دورة في قمة الروعة، من حيث الطرح والمضمون، وكفانا شرفا  ومنة من  الله ان نعرف ونقتضي بامثال هؤلاء الجهابذة امثال  : الامام حسن البنا ، الامام الغزالي رحمهم الله  وغيرهم ... نفع الله بنا جميعا وجعلنا نسير على درهم  فيما يرضيه عنا واقر اعين رسول الله بنا 🤲🏻"
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":2,
		"name": "كفرقرع",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":3,
		"name": "الفريديس",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":4,
		"name": "نحف",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":5,
		"name": "كفركنّا",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"قالوا عن مدارس العلوم الشرعية - الممرض هشام عواودة - كفركنا",
                "link":"https://www.youtube.com/watch?v=mMqzdc8kLTc&list=PLGbHsjcWVUt-gemaZulpjF9oJ6MW3J2vo&index=1&ab_channel=%D9%85%D8%AF%D8%A7%D8%B1%D8%B3%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9"
             },
             "statement":{
                "name":"سبأ عمر محاجنة - يافة الناصرة",
                "link":"",
                "details":"بدأت التغير بحياتي منذ ان دخلت في هذه المدرسة الكريمة ... تهدف الى تغيير كل مسلم نحو ذاته وحياته وخصوصيته ... أشياء كثيرة تعلمتها ولو كانت بسيطة ولكننا لم نعرف قيمتها ... قيمة التعبير والتعلم والرأي يصل بطريقة فعالة ومبسطة .. أتمنى لكم المزيد من التقدم  والنجاح"
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"امنه ابوليل حبيب الله - عين ماهل",
                "link":"",
                "details":"مدرسة العلوم الشرعية ودوراتها المتنوعه اتاحت لنا الفرصة للتعلم امور ديننا من المنزل في اوقات مريحه حتى لا يكون لنا حجة امام الله امام طلب العلم الشرعي .الكثير من المعلومات التي كنت اجهلها او ربما مشاغل الحياة انستنا اياها استطعت اكتسابها وتذاكرها واغتنام اوقاتنا الضائعه في متهات الحياة .أسال الله العظيم ان يبارك في القائمين على العمل الدعوي وان يجعله في ميزان حسناتهم ويجزيهم عنا كل خير"
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"منار خالد دهامشه",
                "link":"",
                "details":"انضممت الى مدرسه العلوم الشرعيه منذ فترة الكورونا وقد تعلمت مساق ثله من الأولين عرفت شخصيات بقمه الروعه لم اكن اعرفهم وبفضل هذه المدرسه اكملت واخذت مساق اصول العشرين مع فضيله الشيخ عبد الرحيم واسلوب وتقديم الشيخ للمعلومات بقمه الروعه وايضا كنت اجهل امور عديده بارك الله بكم وبكل الطاقم المهني الرائع"
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
               "name":"فاطمة خطيب",
               "link":"",
               "details":"السلام عليكم   التحقت بمدرسة العلوم الشرعيه  من سنوات  في طرعان  تعلمنا وفي كفر مندا كذلك وفي كفركنا والحمد لله استفدت من  المدرسه   ودورات العلم كثيرا   حتى اني   تعلمت دور الاصول العشرين مرتين   🤲وقل ربي زدني علما  وبارك الله فيكم  القائمين على هذا المشروع  القيم ولكم دوام التقدم والنجاح"
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":true,
             "video":{
                "name":"قالوا عن مدارس العلوم الشرعية - محمد مصالحة - الرينة",
                "link":"https://www.youtube.com/watch?v=9LOa909ZVAk&list=PLGbHsjcWVUt-gemaZulpjF9oJ6MW3J2vo&index=6&ab_channel=%D9%85%D8%AF%D8%A7%D8%B1%D8%B3%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9"
             },
             "statement":{
               "name":"المربية هدى عيسى",
               "link":"",
               "details":`يعد العلمُ قوة كبيرة فهو أعلى الرتب<br/>
               ويعطي صاحبه طاقة وقوة لا تقدر إذ يقول تبارك وتعالى:-<br/>
               {يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ}<br/>
               فبإنضمامنا لمدرسة العلوم الشرعية نستمد طاقتنا لندير عجلةَ حياتنا بتقوى الله عز وجل.`
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":6,
		"name": "عرّابة",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":7,
		"name": "طمرة",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":true,
             "video":{
                "name":"قالوا عن مدارس العلوم الشرعية - عبد الله شقير خريج اقتصاد وادارة اعمال - طمرة",
                "link":"https://www.youtube.com/watch?v=T5SCJ68yLew&list=PLGbHsjcWVUt-gemaZulpjF9oJ6MW3J2vo&index=3&ab_channel=%D9%85%D8%AF%D8%A7%D8%B1%D8%B3%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9"
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":true,
             "video":{
                "name":"قالوا عن مدارس العلوم الشرعية - محمد عيسى مهجة مدرس رياضيات - حيفا",
                "link":"https://www.youtube.com/watch?v=zgQbBITnc8w&list=PLGbHsjcWVUt-gemaZulpjF9oJ6MW3J2vo&index=4&ab_channel=%D9%85%D8%AF%D8%A7%D8%B1%D8%B3%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9"
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":true,
             "video":{
                "name":"قالوا عن مدارس العلوم الشرعية - موسى حافظ حجازي - طمرة",
                "link":"https://www.youtube.com/watch?v=mslO2Ku5r2A&list=PLGbHsjcWVUt-gemaZulpjF9oJ6MW3J2vo&index=5&ab_channel=%D9%85%D8%AF%D8%A7%D8%B1%D8%B3%D8%A7%D9%84%D8%B9%D9%84%D9%88%D9%85%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9"
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"مرجان حجازي - طمرة",
                "link":"",
                "details":`السلام عليكم..
                مدارس العلوم الشرعيه العظيمه تنفع مختلف البلاد بشتى واختلاف مواضيع العلوم الشرعيه وتفيد غيرها بهذا الكم الهائل من العلوم الشرعيه والتي هي فرض علينا بتعلمها لكي نعبد ونطيع الله على بصيره ونعرف وتزداد افاق معرفتنا اكثر عن ديننا الحنيف لنعرف اكثر عن الحلال والحرام فهنيئُا لمن اخذ بها وتعلمها واستفاد وافاد غيره وعمل بها فأشكر جميع العاملين في هذه المدارس المباركه وجميع الدعاة على إلقائهم الدروس النافعه جزاكم الله خيرًا ونفع بكم الأمه وجعلها بميزان حسناتكم والله يبارك ويوفق وينجح من تعلمها ومن علمها ومن عمل بها اللهم آمين..
                وانصح كل مسلم بالغ عاقل ذكر كان او انثى بتعلم مثل هذه العلوم الشرعيه النافعه والمفيده لينتفع بها في دنياه وآخرته وينال الحسنات والثواب والدرجات العلا في الجنه..
                `
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
               "name":"فاطمة شريف - كفرياسيف",
               "link":"",
               "details":`في ضجة الحياة اليومية وبالذات في زمننا الذي يعج بالاحداث والمتغيرات والفتن نكون بامس الحاجة الى منارات تضيء لنا الطريق وقوارب نجاة تعبر بنا الى بر الامان
               الاشتراك في دورة الاصول العشرين كان له اجمل الوقع في نفسي فقد تلقيت العلم النافع من شيخنا الجليل الدكتور عبد الرحيم خليل  باسلوب سلس بسيط محبب للنفس وفي اجواء اخوية جميلة حيث اجتمعت واخوات لي في الله جاهدت كل منهن نفسها لتاخذ استراحة اسبوعية من مشاغل الحياة ننهل فيها الجزء اليسير من العلم ونتزود بها بالكثير من الطاقات والهمم الايجابية والتعطش لمزيد من العلم النافع
               اشكر القائمين على هذا البرنامج الجميل وادعو كل اخت ان لا تبخل على نفسها بمثل هذه المجالس الطيبة .`
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
               "name":"فاطمة حجازي - طمرة",
               "link":"",
               "details":`ان  الروح والجسد والعقل .. تبحث  دائما  عمن  يرشدها  للتأدب  في الحياة الدنيا ليرضى الله تعالى عنها.
               لذا فالرغبة المنصفة ان نكون أول الملتزمين بدورات مدرسة العلوم الشرعية ونتعمق في أسس المدرسة المحمدية  فنتعلم كيف نبني منهج حياة بتزكية النفس.`
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"المربية أمل أنور حجازي - طمرة",
                "link":"",
                "details":"ارى بمدرسة العلوم الشرعية رسالة سامية لمن يسير بلا هدف٫ويمضي على غير هدى٫ يحاول ان يجد معنى لحياته٫ اخذت الدنيا منه كل شيء عقله وروحه واضاع وقته سدى فلم يدع للاخرة شيئا.فكان الهدف ان نبصر ٫نتدبر ٫نتعلم ونتطلع على الجنة لحظة وننال من النار نظرة ونتقلب في ظلمات القبر برهة. لنعود الى الله وننعم بعبادته ونتفقه باصول دينة لنصل الى الفردوس الاعلى."
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"عايدة علاء الدين - طمرة",
                "link":"",
                "details":` انضممت الى مدرسه العلوم الشرعيه منذ فتره والحمد لله استفدت كثيرا وتعلمت امورا في الدين كثيره كنت اجهلها بدية من تلاوة القرآن الكريم.  وبفضل تلك المجموعه اليوم انا ادرك امورا كنت اجهلها وتعلمت الصبر  واحكام وسنن كانت تمر على يوميا ولم ادرك اهميتها شكرا لكم على مجهودهم معنا واتمنى ان تدوم وتزدهر تلك المدرسه.`
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"المربيّة منال بركات (حمادي) - كابول",
                "link":"",
                "details":`مدرسة العلوم الشّرعية مطلب كل مسلم ومسلمة؛ فالعلم بذاته يستلزم العلم بما سواه؛ لأن من عرف الله تفتحت له أبواب العلم، وأبصر السبيل، واستضاء له الطريق، فلا يحتاج بعد ذلك أكثر من العلم بالله؛ لأن به يفتتح كل مغلق، ويحصل به كل مطلوب.<br/>
                قال تعالى:{وَلَا تَكُونُوا كَالَّذِينَ نَسُوا اللَّهَ فَأَنْسَاهُمْ أَنْفُسَهُمْ}<br/>
               نطلب العلم الشّرعي لأنه به يعصمنا الله من الفتن: والفتن كثرت في هذا الزمان، وستكثر لأنه كلما تقدم الوقت كثرت أسباب الضلال والزيغ وأسباب الشر. <br/>
               أهل العلم هم خلاصة الوجود، وهم الذين بهم يحفظ الله الأمة من الزيغ والضلال، فمن أراد مثل هذه الفضائل؛ فليُقبل على العلم الشّرعي في مدارس العلوم الشرعيّة.
               `
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"الدكتورة سامية عثمان- تخصص نساء",
                "link":"",
                "details":`العلم تهذيبٌ للنفوس وتأديب للقلوب وشفاء للصدور ورفعة لصاحبه وحامله! <br/>
                فهلمّوا معنا لتنهلوا من معين العلم الميسّر ما يقوّم ويعين على بناء الإنسان في داخلكم! <br/>
                ما أحوجنا اليوم لهذه الحلقات، ما أحوجنا لهذه الصحبة!<br/>
                ما أحوجنا للحظات تستغفر لنا بسببها المخلوقات تصديقا لقول رسول الله صلى الله عليه وسلم: "من سلك طريقا يبتغي فيه علما سلك الله به طريقا إلى الجنة، وإن الملائكة لتضع أجنحتها رضاء لطالب العلم وإن العالم ليستغفر له من في السموات ومن في الأرض، حتى الحيتان في الماء، وفضل العالم على العابد كفضل القمر على سائر الكواكب، إن العلماء ورثة الأنبياء، إنَّ الأنبياء لم يورثوا دينارا ولا درهما، إنما ورثوا العلم فمن أخذ به أخذ بحظ وافر".
                `
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":8,
		"name": "أم الفحم",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    },
    {
       "id":9,
		"name": "التعلّم عن بعد",
       "courses":[
          {
             "id":1,
			"name": "تفسير",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":2,
			"name": "عقيدة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":3,
			"name": "السيرة النبويّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":4,
			"name": "ثلّة من الأولين",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":5,
			"name": "عبادات (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":6,
			"name": "عبادات (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":7,
			"name": "تجويد (1)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":8,
			"name": "تجويد (2)",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":9,
			"name": "الأصول العشرين",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":10,
			"name": "أصول فقه",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":11,
			"name": "علوم القرآن وعلوم الحديث",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":12,
			"name": "تزكية",
             "isDone":true,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":13,
			"name": "رجال الفكر والدعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":14,
			"name": "وسائل دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":15,
			"name": "أساليب دعوة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":16,
			"name": "تربية الأولاد في الإسلام",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":17,
			"name": "ثقافة إسلامية",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":18,
			"name": "لغة عربيّة",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":19,
			"name": "المجتمع العربي",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          },
          {
             "id":20,
			"name": "الغزو الفكري",
             "isDone":false,
             "video":{
                "name":"",
                "link":""
             },
             "statement":{
                "name":"",
                "link":"",
                "details":""
             }
          }
       ]
    }
 ]