var teacherOptions = [
    { value: "اختر مدرسًا", text: "اختر مدرسًا" },
    { value: "shiekh_khaled_sakr", text: "الشيخ خالد صقر" },
    { value: "shiekh_abd_alrahem", text: "الشيخ عبد الرحيم خليل" },
    { value: "shiekh_mashhor_fawaz", text: "الشيخ مشهور فوّاز" },
    { value: "shiekh_mahmod_abo_shfea", text: "الشيخ محمود ابو شفيع" },
    { value: "shiekh_muhammad_ayesh", text: "الشيخ محمد عايش" },
    { value: "shiekh_ameer_naffar", text: "الشيخ امير نفار" },
    { value: "shiekh_ehab_khalil", text: "الشيخ ايهاب الشيخ خليل" },
    { value: "shiekh_ehab_khiralla", text: "الشيخ ايهاب خير الله" },
    { value: "shiekh_muhammad_haidare", text: "الشيخ محمد حيادري" },
    { value: "shiekh_raafat_kanaana", text: "الشيخ رأفت كناعنة" },
    { value: "shiekh_badeaa_melhem", text: "الشيخ بديع ملحم" },
    { value: "shiekh_mahmod_khatib", text: "الشيخ محمود خطيب" },
    { value: "shiekh_hilal", text: "الشيخ هلال حسينية" },
    { value: "shiekh_muhamad_aref", text: "الشيخ محمد وتد" },
    { value: "shiekh_mahmod_watad", text: "الشيخ محمود وتد" },
    { value: "shiekh_khaled_zoabi", text: "الشيخ خالد زعبي" },
    { value: "shiekh_abdallah_idres", text: "الشيخ عبد الله إدريس" },
    { value: "shiekh_adi_fares", text: "الشيخ عدي فارس" },
    { value: "shiekh_husam_saeed", text: "الشيخ حسام بن سعيد " },
    { value: "shiekh_yousef_salame", text: "الشيخ يوسف سلامة " },
    { value: "shiekh_suliman_albdor", text: "الشيخ سليمان البدور" },                            
    { value: "hamed", text: "الاستاذ حامد اغبارية" },
    { value: "shiekh_tawfek", text: "الاستاذ توفيق محمد" },
    { value: "shiekh_ahmad_hammad", text: "الشيخ احمد حماد" },
    { value: "hussen_muhammady", text: "الشيخ حسين محمدي" },
    { value: "abd_alrahman_abu_hija", text: "الشيخ عبد الرحمن ابو الهيجاء" },
    { value: "ali_kamal", text: "الشيخ علي كمال" },
    { value: "mahde_zahalka", text: "الشيخ مهدي زحالقة" },
    { value: "orsan_hajajra", text: "الشيخ عرسان حجاجرة" },
    { value: "mansor_atamnh", text: "الأستاذ منصور عثامنة" },
    { value: "muhammad_shalabe", text: "الأستاذ محمد شلبي" },
    { value: "abdallah_shqer", text: "الأستاذ عبد الله شقير" },
    { value: "nael_fawaz", text: "الشيخ نائل فواز" },
    { value: "anas_suleman", text: "الدكتور انس سليمان" },
    { value: "marwan_jbara", text: "الشيخ مروان جبارة" },
    { value: "tawfek_hathot", text: "الشيخ توفيق حتحوت" },
    { value: "maamon_mahamed", text: "الشيخ مأمون محاميد" },
    { value: "ali_jabaren", text: "الشيخ علي جبارين" },
    { value: "muhammad_shehade", text: "الشيخ محمد شحادة" },
    { value: "husam_abu_lel", text: "الشيخ حسام أبو ليل" },
    { value: "ahmad_saleh", text: "الشيخ أحمد صالح" },
    { value: "okht_nihal_okare", text: "الأخت نهال عكري" },
    { value: "okht_sawsan_masarwe", text: "الأخت سوسن مصاروة" },
    { value: "okht_eiman_abed", text: "الأخت ايمان عبيد" },
    { value: "okht_asmaa_kryeem", text: "الأخت اسماء كريم" },
    { value: "okht_tasnem_taha", text: "الأخت تسنيم طه" },
    { value: "okht_layla_mawase", text: "الأخت ليلى مواسي" },
    { value: "okht_salam_tayeh", text: "الأخت سلام تايه" },
    { value: "okht_fadwa_ebed", text: "الأخت فدوى عبيد" },
    { value: "okht_ahlam_igbaria", text: "الأخت أحلام إغبارية" },
    { value: "okht_ikhlas_abo_shekha", text: "الأخت إخلاص أبو شيخة" },
    { value: "okht_asia_zreqe", text: "الأخت آسيا زريقي" },
    { value: "okht_maria_mahajna", text: "الأخت ماريا محاجنة" },
    { value: "okht_amna_hijazi", text: "الأخت آمنة حجازي" },
    // Add more options as needed
];

var subjectOptions = [
    { value: "اختر موضوعا", text: "اختر موضوعا" },
    { value: "tfser", text: "تفسير القران" },
    { value: "sera", text: "السيرة النبوية" },
    { value: "abadat", text: "عبادات 1" },
    { value: "abadat2", text: "عبادات 2" },
    { value: "tajwed", text: "تجويد 1" },
    { value: "tajwed2", text: "تجويد 2" },
    { value: "trbyat_awlad", text: "تربية الاولاد" },
    { value: "olom_hadeth", text: "علوم حديث وقرآن" },
    { value: "osol20", text: "الاصول العشرين" },
    { value: "thkafa_islamya", text: "الثقافة الاسلامية" },
    { value: "arabic_lang", text: "اللغة العربية" },
    { value: "tzkya", text: "التزكية" },
    { value: "thula_mn_awlen", text: "ثُلّةٌ من الأولين" },
    { value: "rjal_alfekr", text: "رجال الفكر" },
    { value: "gzw_fkre", text: "الغزو الفكري" },
    { value: "mjtmaa_arabe", text: "المجتمع العربي" },
    { value: "osol_feqh", text: "اصول الفقه" },
    { value: "wsael_daawa", text: "وسائل دعوة" },
    { value: "aqeda1", text: "العقيدة الاسلامية" },
    { value: "asaleb_daawa", text: "اساليب الدعوة" },

    // Add more options as needed
];

var locationOptions = [
    { value: "مكان الدورة", text: "مكان الدورة" },
    { value: "kofr_kna", text: "كفركنا - قاعة مسجد عثمان بن عفان" },
    { value: "qlnsawa", text: "قلنسوة - المدرسة الاهلية" },
    { value: "arraba", text: "عرابة - مركز حفيدات عائشة - مبنى الوقف" },
    { value: "fredes", text: "الفرديس - قاعة مسجد الفردوس - الظهرات" },
    { value: "tamra", text: "طمرة - مسجد معاذ بن جبل" },
    { value: "kofr_kara", text: "كفرقرع - مسجد الصندحاوي" },
    { value: "um_alfahm_gen", text: "أم الفحم - مركز البينة، بناية الشافعي" },
    { value: "um_alfahm", text: "أم الفحم - مركز آفاق بصائر الخير" },
    { value: "nahaf", text: "نحف - مسجد الرحمن" },
    { value: "abu_snan", text: "ابو سنان - قاعة مسجد الرحمة" },
    { value: "naqab", text: "اللقيّة - مسجد عمر بن الخطّاب حارة البدور" },
    { value: "aelot", text: "عيلوط - مدرسة الهدى" },
    { value: "jat", text: "جتّ - ديوان مسجد بلال بن رباح" },
    { value: "online", text: "التعليم عن بعد" },

    // Add more options as needed
];
